---
author: "lea wölbert"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

smooth muscle cells.

Related to Figure results 2.

## Libraries

```{r libraries, message = FALSE}

library(SingleCellExperiment)
library(rlist)
library(tidyverse)
library(eulerr)
library(gridExtra)
library(scater)
library(ggpubr)
library(scran)
library("factoextra")

```

## Load

### Code

```{r load_code, message = FALSE}

source(file = "../../code/filepath.R")
source(file = "../../code/colors.R")
source(file = "../../interactome/functions/cpi_functions_calculation.R")
source(file = "../../interactome/functions/cpi_functions_analysis.R")

```

### Objects

```{r}

sce_all <- readRDS(file = paste0(
  filepath_lv1, "data/sce_objects/mmus/mmus_SCE"))

mmus_yng_sce_ds <- readRDS(file = paste0(
    filepath_lv1, "data/sce_objects/mmus/mmus_young_SCE_ds"))
mmus_old_sce_ds <- readRDS(file = paste0(
    filepath_lv1, "data/sce_objects/mmus/mmus_old_SCE_ds"))

sce_all <- cbind(mmus_yng_sce_ds, mmus_old_sce_ds)
#assays(sce_all)$logcounts <- assays(sce_all)$downsampled

```

## A

Umap of Smooth muscle cells and various genes

```{r}

plot_a <- plotUMAP(sce_all,  colour_by = "Tagln",
                   point_size = 0.4, 
                  point_alpha = 1)+
  scale_color_gradientn("Tagln ", colors = c("black", "darkorange3", "orange", "lightgoldenrod"))

plot_b <- plotUMAP(sce_all,  colour_by = "Acta2",
                   point_size = 0.4, 
                  point_alpha = 1)+
  scale_color_gradientn("Acta2 ", colors = c("black", "darkorange3", "orange", "lightgoldenrod"))

plot_c <- plotUMAP(sce_all,  colour_by = "Myh11",
                   point_size = 0.4, 
                  point_alpha = 1)+
  scale_color_gradientn("Myh11 ", colors = c("black", "darkorange3", "orange", "lightgoldenrod"))


plot_a
plot_b
plot_c

```

```{r}

plot_A <- plot_a+
   # base theme
    theme_classic()+
    theme(axis.text = element_text(size = 11),
          axis.title = element_text(size = 13),
          legend.title = element_text(size = 12, face = "bold"),
          legend.text = element_text(size = 11),
          plot.title = element_text(size = 14, face = "bold"))+
  theme(plot.background = element_blank(),
        panel.background = element_blank(),
        legend.background = element_blank())+
  # individual additions
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.title = element_text(size = 12, face = "bold.italic"))

plot_A

```

```{r}

plot_B <- plot_b+
   # base theme
    theme_classic()+
    theme(axis.text = element_text(size = 11),
          axis.title = element_text(size = 13),
          legend.title = element_text(size = 12, face = "bold"),
          legend.text = element_text(size = 11),
          plot.title = element_text(size = 14, face = "bold"))+
  theme(plot.background = element_blank(),
        panel.background = element_blank(),
        legend.background = element_blank())+
  # individual additions
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.title = element_text(size = 12, face = "bold.italic"))

plot_B

```

```{r}

plot_C <- plot_c+
   # base theme
    theme_classic()+
    theme(axis.text = element_text(size = 11),
          axis.title = element_text(size = 13),
          legend.title = element_text(size = 12, face = "bold"),
          legend.text = element_text(size = 11),
          plot.title = element_text(size = 14, face = "bold"))+
  theme(plot.background = element_blank(),
        panel.background = element_blank(),
        legend.background = element_blank())+
  # individual additions
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.title = element_text(size = 12, face = "bold.italic"))

plot_C

```

```{r}

figure_s4_abc <- ggarrange(
  ncol = 3,
  plot_A+ggtitle("Smooth muscle marker gene expression"),
  plot_B+ggtitle(""),
  plot_C+ggtitle("")
)

figure_s4_abc

ggsave("images/figure_s4_abc.png",
  figure_s4_abc,
  width = 17*0.787402,
  height = 4.5*0.787402,
  units = c("in"),
  dpi = 150)

```
